AWSTemplateFormatVersion: "2010-09-09"
Description: |
  This template launches an EC2 instance with a sec grp that enable SSH.

Resources:
  Webserver: # LogicID yerine yazıldı
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-0b5eea76982371e91 # kendi instance sayfandan oluşturulan ImageId'ni gir.
      InstanceType: t2.micro
      KeyName: Ferdaco # kendi oluşturduğun PeKey'ini yazman gerekiyor
      SecurityGroups:
        - !Ref WebserverSecGrp # buraya bu şablon yerine securtyID de yazabilirsin ama ayrı bir parametre gerekiyor.
      Tags: # Tag'in nasıl yazılması gerektiği aşağıya yazıldı.
        - Key:  Name
          Value:  CFN-Instance
        - Key:  Environment
          Value:  Dev
  WebserverSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: enables SSH # Required
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

